-- PostgreSQL is the portal's only transactional control plane and queue.
-- All identifiers are UUIDs generated by the application to keep this migration
-- extension-free and deployable without database-superuser privileges.

CREATE TABLE portal_users (
    id uuid PRIMARY KEY,
    email text NOT NULL UNIQUE CHECK (email = lower(email)),
    password_hash text NOT NULL,
    is_site_admin boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE portal_sessions (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES portal_users(id) ON DELETE CASCADE,
    token_hash text NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX portal_sessions_expiry_idx ON portal_sessions (expires_at);

CREATE TABLE portal_teams (
    id uuid PRIMARY KEY,
    slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
    name text NOT NULL CHECK (length(trim(name)) > 0),
    created_by uuid NOT NULL REFERENCES portal_users(id),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE portal_team_memberships (
    team_id uuid NOT NULL REFERENCES portal_teams(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES portal_users(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('team_leader', 'team_member')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (team_id, user_id)
);
CREATE INDEX portal_memberships_user_idx ON portal_team_memberships (user_id, team_id);

CREATE TABLE portal_object_references (
    id uuid PRIMARY KEY,
    team_id uuid NOT NULL REFERENCES portal_teams(id) ON DELETE RESTRICT,
    provider text NOT NULL CHECK (length(trim(provider)) > 0),
    container text NOT NULL CHECK (length(trim(container)) > 0),
    object_key text NOT NULL CHECK (length(trim(object_key)) > 0),
    sha256 text NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    content_type text NOT NULL CHECK (length(trim(content_type)) > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (team_id, provider, container, object_key, sha256),
    UNIQUE (id, team_id)
);

CREATE OR REPLACE FUNCTION portal_reject_object_reference_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'portal object references are immutable';
END;
$$;
CREATE TRIGGER portal_object_references_immutable
    BEFORE UPDATE OR DELETE ON portal_object_references
    FOR EACH ROW EXECUTE FUNCTION portal_reject_object_reference_mutation();

CREATE TABLE portal_team_proxy_credentials (
    id uuid PRIMARY KEY,
    team_id uuid NOT NULL REFERENCES portal_teams(id) ON DELETE CASCADE,
    label text NOT NULL CHECK (length(trim(label)) > 0),
    created_by uuid NOT NULL REFERENCES portal_users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    retired_at timestamptz,
    UNIQUE (team_id, label),
    UNIQUE (id, team_id)
);

CREATE TABLE portal_team_proxy_credential_versions (
    id uuid PRIMARY KEY,
    credential_id uuid NOT NULL,
    team_id uuid NOT NULL,
    version integer NOT NULL CHECK (version > 0),
    provider text NOT NULL CHECK (length(trim(provider)) > 0),
    config_ciphertext bytea NOT NULL CHECK (octet_length(config_ciphertext) > 0),
    key_id text NOT NULL CHECK (length(trim(key_id)) > 0),
    is_active boolean NOT NULL DEFAULT true,
    created_by uuid NOT NULL REFERENCES portal_users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (credential_id, team_id)
        REFERENCES portal_team_proxy_credentials (id, team_id) ON DELETE CASCADE,
    UNIQUE (credential_id, version),
    UNIQUE (id, team_id)
);
CREATE UNIQUE INDEX portal_active_credential_version_idx
    ON portal_team_proxy_credential_versions (credential_id)
    WHERE is_active;

CREATE TABLE portal_queue_control (
    singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
    max_active_jobs smallint NOT NULL CHECK (max_active_jobs = 5)
);
INSERT INTO portal_queue_control (singleton, max_active_jobs) VALUES (true, 5);

-- Admission, cancellation, completion, and promotion all lock this one row in their
-- transaction. The repository issues the equivalent SELECT directly so the lock is
-- visible beside each transition; this function is also available to SQL-only tools.
CREATE OR REPLACE FUNCTION portal_lock_queue_control()
RETURNS smallint LANGUAGE plpgsql AS $$
DECLARE maximum smallint;
BEGIN
    SELECT max_active_jobs INTO maximum
      FROM portal_queue_control
     WHERE singleton = true
     FOR UPDATE;
    RETURN maximum;
END;
$$;

CREATE TABLE portal_jobs (
    id uuid PRIMARY KEY,
    team_id uuid NOT NULL REFERENCES portal_teams(id) ON DELETE RESTRICT,
    submitted_by uuid NOT NULL REFERENCES portal_users(id),
    credential_version_id uuid NOT NULL,
    input_object_id uuid NOT NULL,
    filename text NOT NULL CHECK (length(trim(filename)) > 0),
    sources text[] NOT NULL CHECK (
        cardinality(sources) > 0
        AND sources <@ ARRAY['osiptel', 'sunat', 'sunat_reps']::text[]
    ),
    state text NOT NULL CHECK (
        state IN ('queued', 'running', 'cancelling', 'completed', 'failed', 'cancelled')
    ),
    queue_sequence bigint GENERATED ALWAYS AS IDENTITY UNIQUE,
    lease_owner text,
    lease_fence bigint NOT NULL DEFAULT 0 CHECK (lease_fence >= 0),
    lease_expires_at timestamptz,
    terminal_reason text,
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (credential_version_id, team_id)
        REFERENCES portal_team_proxy_credential_versions (id, team_id) ON DELETE RESTRICT,
    FOREIGN KEY (input_object_id, team_id)
        REFERENCES portal_object_references (id, team_id) ON DELETE RESTRICT,
    UNIQUE (id, team_id),
    CHECK (
        (state IN ('queued', 'running', 'cancelling') AND finished_at IS NULL)
        OR state IN ('completed', 'failed', 'cancelled')
    )
);
CREATE INDEX portal_jobs_fifo_idx ON portal_jobs (queue_sequence) WHERE state = 'queued';
CREATE INDEX portal_jobs_active_idx ON portal_jobs (state, queue_sequence)
    WHERE state IN ('running', 'cancelling');
CREATE INDEX portal_jobs_team_idx ON portal_jobs (team_id, queue_sequence DESC);
CREATE INDEX portal_jobs_lease_idx ON portal_jobs (lease_expires_at)
    WHERE state IN ('running', 'cancelling');

CREATE TABLE portal_job_items (
    id uuid PRIMARY KEY,
    job_id uuid NOT NULL REFERENCES portal_jobs(id) ON DELETE CASCADE,
    team_id uuid NOT NULL REFERENCES portal_teams(id) ON DELETE RESTRICT,
    ordinal integer NOT NULL CHECK (ordinal > 0),
    document text NOT NULL CHECK (length(trim(document)) > 0),
    source text NOT NULL CHECK (source IN ('', 'osiptel', 'sunat', 'sunat_reps')),
    state text NOT NULL CHECK (
        state IN ('pending', 'running', 'published', 'excluded', 'failed', 'cancelled')
    ),
    reason text,
    lease_owner text,
    lease_fence bigint NOT NULL DEFAULT 0 CHECK (lease_fence >= 0),
    lease_expires_at timestamptz,
    result_object_id uuid,
    published_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (job_id, ordinal, source),
    FOREIGN KEY (job_id, team_id)
        REFERENCES portal_jobs (id, team_id) ON DELETE CASCADE,
    FOREIGN KEY (result_object_id, team_id)
        REFERENCES portal_object_references (id, team_id) ON DELETE RESTRICT,
    CHECK ((state = 'excluded') = (source = '')),
    CHECK ((state = 'published') = (result_object_id IS NOT NULL))
);
CREATE INDEX portal_job_items_claim_idx
    ON portal_job_items (job_id, ordinal) WHERE state = 'pending';
CREATE INDEX portal_job_items_published_idx
    ON portal_job_items (document, job_id) WHERE state = 'published';
CREATE INDEX portal_job_items_lease_idx
    ON portal_job_items (lease_expires_at) WHERE state = 'running';

CREATE TABLE portal_job_events (
    id uuid PRIMARY KEY,
    job_id uuid NOT NULL REFERENCES portal_jobs(id) ON DELETE CASCADE,
    sequence bigint GENERATED ALWAYS AS IDENTITY,
    event_type text NOT NULL CHECK (length(trim(event_type)) > 0),
    actor_id uuid REFERENCES portal_users(id) ON DELETE SET NULL,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (job_id, sequence)
);
CREATE INDEX portal_job_events_job_idx ON portal_job_events (job_id, sequence);

CREATE TABLE portal_notification_outbox (
    id uuid PRIMARY KEY,
    event_id uuid NOT NULL REFERENCES portal_job_events(id) ON DELETE CASCADE,
    channel text NOT NULL CHECK (channel IN ('in_app', 'email', 'kapso_whatsapp')),
    payload jsonb NOT NULL,
    state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'sending', 'sent', 'failed')),
    available_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (event_id, channel)
);
CREATE INDEX portal_notification_outbox_claim_idx
    ON portal_notification_outbox (available_at, id) WHERE state = 'pending';

CREATE TABLE portal_notification_deliveries (
    id uuid PRIMARY KEY,
    outbox_id uuid NOT NULL REFERENCES portal_notification_outbox(id) ON DELETE CASCADE,
    attempt integer NOT NULL CHECK (attempt > 0),
    provider_message_id text,
    outcome text NOT NULL CHECK (outcome IN ('sent', 'failed')),
    detail text,
    attempted_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (outbox_id, attempt)
);

CREATE TABLE portal_exports (
    id uuid PRIMARY KEY,
    job_id uuid NOT NULL REFERENCES portal_jobs(id) ON DELETE CASCADE,
    team_id uuid NOT NULL REFERENCES portal_teams(id) ON DELETE RESTRICT,
    requested_by uuid NOT NULL REFERENCES portal_users(id),
    object_id uuid NOT NULL,
    format text NOT NULL CHECK (format IN ('csv', 'jsonl')),
    created_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (object_id, team_id)
        REFERENCES portal_object_references (id, team_id) ON DELETE RESTRICT,
    FOREIGN KEY (job_id, team_id)
        REFERENCES portal_jobs (id, team_id) ON DELETE CASCADE,
    UNIQUE (job_id, format, object_id)
);
CREATE INDEX portal_exports_job_idx ON portal_exports (job_id, created_at DESC);

CREATE TABLE portal_worker_registrations (
    id text PRIMARY KEY,
    hostname text NOT NULL CHECK (length(trim(hostname)) > 0),
    sources text[] NOT NULL CHECK (
        cardinality(sources) > 0
        AND sources <@ ARRAY['osiptel', 'sunat', 'sunat_reps']::text[]
    ),
    capacity smallint NOT NULL CHECK (capacity > 0),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    registered_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX portal_workers_seen_idx ON portal_worker_registrations (last_seen_at DESC);
