from __future__ import annotations


RUN_START = "run_start"
RUN_SUMMARY = "run_summary"
RUCS_UNROUTED = "rucs_unrouted"
SITE_SELECTED = "site_selected"
SITE_SUMMARY = "site_summary"
PROVIDER_SELECTED = "provider_selected"
STICKY_ACQUIRE = "sticky_acquire"
STICKY_RELEASE_FAILED = "sticky_release_failed"
SESSION_RELEASE_SKIPPED = "session_release_skipped"
SESSION_READY = "session_ready"
FETCH_PAGE_START = "fetch_page_start"
FETCH_PAGE_OK = "fetch_page_ok"
SITE_REQUEST_FAILED = "site_request_failed"
LOOKUP_OK = "lookup_ok"
LOOKUP_NOT_FOUND = "lookup_not_found"
LOOKUP_FAILED = "lookup_failed"
WORKER_UNHANDLED_EXCEPTION = "worker_unhandled_exception"
EGRESS_IP_UNRESOLVED = "egress_ip_unresolved"
CIRCUIT_OPEN = "circuit_open"
CIRCUIT_CLOSED = "circuit_closed"
