[tools]
uv = "0.11.7"
python = "3.14.4"

[tasks.install]
run = "uv sync"

[tasks.update]
run = "uv sync -U"

[tasks.outdated]
run = "uv pip list --outdated"

[tasks.format]
run = ["uv run ruff format", "uv run ruff check --fix"]

[tasks.check]
run = ["uv run mypy ."]

[tasks.test]
run = "uv run pytest"

[tasks.build]
run = ["rm -rf dist build", "uv run pyinstaller robot.spec"]
